pipeline {
    agent any

    tools {
        maven 'maven 3.8.6'
    }

    stages {
        stage('Clean') {
            steps {
                sh "mvn clean install -pl /api-gateway"
            }
        }
       stage('Test') {
            steps {
                sh "mvn test -pl /api-gateway"
            }
       }
       stage('Package') {
           steps {
               sh "mvn package -pl /api-gateway"
           }
      }
   }
}