pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                sh "mvn clean install -pl /order-service"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test -pl /order-service"
            }
        }
        stage('Build Image') {
                steps {
                    sh 'docker build -t lopesdev/order-service:latest order-service'
                }
        }
        stage('DockerHub Login') {
                environment {
                    DOCKERHUB_CREDENTIALS = credentials('dockerhub')
                }
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push Image') {
            steps {
                sh 'docker push lopesdev/order-service:latest'
            }
        }
	}
        post {
            always {
                sh 'docker logout'
                cleanWs()
                sh 'docker rmi lopesdev/order-service:latest'
            }
        }
}