apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels: 
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service 
          image: lopesdev/inventory-service
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8083