apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels: 
    app: inventory-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service 
          image: inventory-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30005
