apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-deployment
  labels: 
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mysql-secret
                  value: mysql-db-url
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef: 
                  name: mysql-configmap
                  value: mysql-db-url
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
