apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels: 
    app: notification-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service 
          image: notification-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_SERVER
              value: kafka-cluster
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
