apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels: 
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service 
          image: order-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "my-secret-pw"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: db-host
            - name: INVENTORY_HOST
              value: inventory-service
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef: 
                  name: order-configmap
                  key: kafka-url
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
