apiVersion: v1 # Defining PVC for Mysql Storage, dynamically provisioned by cluster
kind: PersistentVolumeClaim
metadata:
  name: queue-pv-claim
  labels:
    app: rabbitmq-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq-service
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: rabbitmq-service
  template:
    metadata:
      labels:
        app: rabbitmq-service
    spec:
      containers:
        - name: rabbitmq-service
          image: rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          volumeMounts:
            - name: queue-persistent-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: queue-persistent-storage
          persistentVolumeClaim:
            claimName: queue-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq-service
  type: NodePort
  ports:
    - name: amqt
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 32000
